library(tidyverse)
library(magrittr)
library(openxlsx)
library(readxl)
library(writexl)
library(reshape2)
library(skimr)
library(janitor)
library(lubridate)
library(rio)

library(tidymodels)
library(plyr)
library(ggrepel)
library(officer)
library(ggtext)
library(simmer)
library(arulesViz)
library(Matrix)
library(palmerpenguins)
library(quantmod)
library(tseries)
library(timeSeries)
library(forecast)
library(xts)
library(flextable)
library(tidyquant)
library(timetk)
library(fs)
library(gt)
library(webshot)
library(plotly)
library(epiDisplay)
library(questionr)
library(summarytools)
library(broom)
library(fontawesome)
library(htmltools)
library(rmarkdown)
library(DescTools)
library(MASS)
library(readxlsb)
library(RODBC)
library(data.table)
library(plotrix)
library(reticulate)
library(maps)
library(mapproj)
library(ggfortify)
library(statsr)
library(devtools)
library(swirl)  # R tutorial
library(vip)
library(knitr)
library(pander)  
library(xtable)
library(jtools) # For tabulating and visualizing results from multiple regression models
library(ggstance)
library(huxtable)
library(broom.mixed)
library(modeltime)
library(gridExtra)
library(caret)
library(rayshader)
library(ggmap)
library(e1071)
library(class)
library(tree)  # tree plot, machine learning algorithm
library(party) # tree plot, powerful algorithm
library(visdat) # visualizing the missing data
library(naniar) # visualizing working with missing data
library(simputation) # For simple imputation
library(corrplot) # correlation
library(PerformanceAnalytics) # correlation
library(GGally)
library(dbscan)
library(pryr)  # size check 
library(dbscan)
library(factoextra)
library(randomForest)
library(nnet)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(vader)   # text sentiment analysis
library(gcookbook)
library(igraph)
library(tidygraph) 
library(network)  # network EDA
library(igraph)
library(tidygraph)
library(ggraph)
library(visNetwork)
library(networkD3)
library(DBI) # For SQL writing (connect to data bases)
library(RSQLite) # For SQL writing (data base)
library(lasso2)  # machine learning (regularization)
library(tidytext)
library(Rcpp)
library(bizdays)
library(nycflights13)
library(textdata)  # for dataset (sentiment analysis)
library(ppsr)
library(correlationfunnel)
library(tinytex)
library(mstrio) # MicroStrategy
library(viridis)
library(marmap)  # map
library(leaflet)  # map
library(xgboost)  # for categorical logistics linear regression
library(infer)
library(recipes)
library(hexbin)
library(cluster)  # segmentation machine learning analysis
library(DataExplorer) # This is crazy package.. tips are in library - EDA and ETL Both under DataExplorer section 
library(directlabels)
library(gghighlight)
library(ggthemes)
library(ggcorrplot)
library(ggalt)
library(ggalluvial)
library(packcircles)
library(workflows)
library(flexdashboard)
library(tufte)
library(neuralnet)
library(waterfalls)
library(tm)         # word cloud
library(SnowballC)  # word cloud
library(wordcloud)  # word cloud
library(RColorBrewer) # word cloud
library(RCurl) # word cloud
library(XML) # word cloud
library(visreg)
library(mosaicData)
library(survival)
library(survminer)
library(rpart)
library(CGPfunctions)
library(tune)
library(scales)
library(treemap)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(magick)
library(gganimate)
library(gifski)
library(transformr)
library(esquisse)
library(modeldata)
library(babynames)
library(hrbrthemes)
library(UScensus2010)
library(glmnet)   # for machine learning
library(textrecipes)  
library(themis)
library(tidylo)
library(stopwords)
library(xaringan)
library(mlbench)
library(e1071)
library(ranger)
library(DataEditR)
library(datapasta)
library(ggridges)   # ggplot2 graphs combine
library(gghalves)
library(grafify)
library(ggside)


# Shiny Packages
library(shiny)
library(shinydashboard)
library(shinycssloaders)
library(shinyFeedback)
library(shinythemes)
library(gapminder)
library(ggforce)
library(gh)
library(globals)
library(openintro)
library(profvis)
library(RSQLite)
library(testthat)
library(thematic)
library(tidyverse)
library(vroom)
library(waiter)
library(xml2)
library(zeallot)
library(bslib)

library(shinyuieditor)
# install.packages("remotes")
# remotes::install_github("rstudio/shinyuieditor")



